INSERT INTO `country` (`id`,`code`,`name`) VALUES (1,'ZW','Zimbabwe');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (2,'AF','Afghanistan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (3,'AL','Albania');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (4,'DZ','Algeria');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (5,'DS','American Samoa');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (6,'AD','Andorra');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (7,'AO','Angola');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (8,'AI','Anguilla');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (9,'AQ','Antarctica');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (10,'AG','Antigua and Barbuda');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (11,'AR','Argentina');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (12,'AM','Armenia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (13,'AW','Aruba');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (14,'AU','Australia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (15,'AT','Austria');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (16,'AZ','Azerbaijan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (17,'BS','Bahamas');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (18,'BH','Bahrain');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (19,'BD','Bangladesh');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (20,'BB','Barbados');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (21,'BY','Belarus');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (22,'BE','Belgium');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (23,'BZ','Belize');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (24,'BJ','Benin');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (25,'BM','Bermuda');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (26,'BT','Bhutan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (27,'BO','Bolivia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (28,'BA','Bosnia and Herzegovina');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (29,'BW','Botswana');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (30,'BV','Bouvet Island');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (31,'BR','Brazil');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (32,'IO','British Indian Ocean Territory');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (33,'BN','Brunei Darussalam');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (34,'BG','Bulgaria');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (35,'BF','Burkina Faso');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (36,'BI','Burundi');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (37,'KH','Cambodia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (38,'CM','Cameroon');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (39,'CA','Canada');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (40,'CV','Cape Verde');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (41,'KY','Cayman Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (42,'CF','Central African Republic');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (43,'TD','Chad');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (44,'CL','Chile');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (45,'CN','China');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (46,'CX','Christmas Island');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (47,'CC','Cocos (Keeling) Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (48,'CO','Colombia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (49,'KM','Comoros');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (50,'CG','Congo');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (51,'CK','Cook Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (52,'CR','Costa Rica');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (53,'HR','Croatia (Hrvatska)');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (54,'CU','Cuba');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (55,'CY','Cyprus');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (56,'CZ','Czech Republic');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (57,'DK','Denmark');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (58,'DJ','Djibouti');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (59,'DM','Dominica');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (60,'DO','Dominican Republic');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (61,'TP','East Timor');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (62,'EC','Ecuador');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (63,'EG','Egypt');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (64,'SV','El Salvador');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (65,'GQ','Equatorial Guinea');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (66,'ER','Eritrea');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (67,'EE','Estonia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (68,'ET','Ethiopia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (69,'FK','Falkland Islands (Malvinas)');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (70,'FO','Faroe Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (71,'FJ','Fiji');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (72,'FI','Finland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (73,'FR','France');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (74,'FX','France, Metropolitan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (75,'GF','French Guiana');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (76,'PF','French Polynesia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (77,'TF','French Southern Territories');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (78,'GA','Gabon');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (79,'GM','Gambia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (80,'GE','Georgia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (81,'DE','Germany');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (82,'GH','Ghana');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (83,'GI','Gibraltar');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (84,'GK','Guernsey');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (85,'GR','Greece');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (86,'GL','Greenland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (87,'GD','Grenada');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (88,'GP','Guadeloupe');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (89,'GU','Guam');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (90,'GT','Guatemala');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (91,'GN','Guinea');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (92,'GW','Guinea-Bissau');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (93,'GY','Guyana');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (94,'HT','Haiti');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (95,'HM','Heard and Mc Donald Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (96,'HN','Honduras');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (97,'HK','Hong Kong');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (98,'HU','Hungary');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (99,'IS','Iceland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (100,'IN','India');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (101,'IM','Isle of Man');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (102,'ID','Indonesia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (103,'IR','Iran (Islamic Republic of)');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (104,'IQ','Iraq');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (105,'IE','Ireland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (106,'IL','Israel');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (107,'IT','Italy');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (108,'CI','Ivory Coast');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (109,'JE','Jersey');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (110,'JM','Jamaica');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (111,'JP','Japan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (112,'JO','Jordan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (113,'KZ','Kazakhstan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (114,'KE','Kenya');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (115,'KI','Kiribati');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (116,'KP','Korea, Democratic People\'s Republic of');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (117,'KR','Korea, Republic of');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (118,'XK','Kosovo');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (119,'KW','Kuwait');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (120,'KG','Kyrgyzstan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (121,'LA','Lao People\'s Democratic Republic');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (122,'LV','Latvia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (123,'LB','Lebanon');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (124,'LS','Lesotho');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (125,'LR','Liberia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (126,'LY','Libyan Arab Jamahiriya');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (127,'LI','Liechtenstein');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (128,'LT','Lithuania');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (129,'LU','Luxembourg');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (130,'MO','Macau');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (131,'MK','Macedonia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (132,'MG','Madagascar');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (133,'MW','Malawi');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (134,'MY','Malaysia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (135,'MV','Maldives');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (136,'ML','Mali');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (137,'MT','Malta');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (138,'MH','Marshall Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (139,'MQ','Martinique');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (140,'MR','Mauritania');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (141,'MU','Mauritius');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (142,'TY','Mayotte');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (143,'MX','Mexico');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (144,'FM','Micronesia, Federated States of');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (145,'MD','Moldova, Republic of');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (146,'MC','Monaco');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (147,'MN','Mongolia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (148,'ME','Montenegro');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (149,'MS','Montserrat');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (150,'MA','Morocco');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (151,'MZ','Mozambique');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (152,'MM','Myanmar');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (153,'NA','Namibia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (154,'NR','Nauru');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (155,'NP','Nepal');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (156,'NL','Netherlands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (157,'AN','Netherlands Antilles');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (158,'NC','New Caledonia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (159,'NZ','New Zealand');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (160,'NI','Nicaragua');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (161,'NE','Niger');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (162,'NG','Nigeria');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (163,'NU','Niue');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (164,'NF','Norfolk Island');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (165,'MP','Northern Mariana Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (166,'NO','Norway');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (167,'OM','Oman');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (168,'PK','Pakistan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (169,'PW','Palau');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (170,'PS','Palestine');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (171,'PA','Panama');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (172,'PG','Papua New Guinea');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (173,'PY','Paraguay');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (174,'PE','Peru');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (175,'PH','Philippines');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (176,'PN','Pitcairn');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (177,'PL','Poland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (178,'PT','Portugal');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (179,'PR','Puerto Rico');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (180,'QA','Qatar');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (181,'RE','Reunion');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (182,'RO','Romania');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (183,'RU','Russian Federation');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (184,'RW','Rwanda');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (185,'KN','Saint Kitts and Nevis');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (186,'LC','Saint Lucia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (187,'VC','Saint Vincent and the Grenadines');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (188,'WS','Samoa');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (189,'SM','San Marino');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (190,'ST','Sao Tome and Principe');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (191,'SA','Saudi Arabia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (192,'SN','Senegal');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (193,'RS','Serbia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (194,'SC','Seychelles');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (195,'SL','Sierra Leone');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (196,'SG','Singapore');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (197,'SK','Slovakia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (198,'SI','Slovenia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (199,'SB','Solomon Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (200,'SO','Somalia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (201,'ZA','South Africa');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (202,'GS','South Georgia South Sandwich Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (203,'ES','Spain');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (204,'LK','Sri Lanka');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (205,'SH','St. Helena');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (206,'PM','St. Pierre and Miquelon');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (207,'SD','Sudan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (208,'SR','Suriname');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (209,'SJ','Svalbard and Jan Mayen Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (210,'SZ','Swaziland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (211,'SE','Sweden');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (212,'CH','Switzerland');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (213,'SY','Syrian Arab Republic');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (214,'TW','Taiwan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (215,'TJ','Tajikistan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (216,'TZ','Tanzania, United Republic of');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (217,'TH','Thailand');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (218,'TG','Togo');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (219,'TK','Tokelau');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (220,'TO','Tonga');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (221,'TT','Trinidad and Tobago');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (222,'TN','Tunisia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (223,'TR','Turkey');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (224,'TM','Turkmenistan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (225,'TC','Turks and Caicos Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (226,'TV','Tuvalu');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (227,'UG','Uganda');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (228,'UA','Ukraine');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (229,'AE','United Arab Emirates');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (230,'GB','United Kingdom');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (231,'US','United States');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (232,'UM','United States minor outlying islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (233,'UY','Uruguay');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (234,'UZ','Uzbekistan');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (235,'VU','Vanuatu');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (236,'VA','Vatican City State');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (237,'VE','Venezuela');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (238,'VN','Vietnam');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (239,'VG','Virgin Islands (British)');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (240,'VI','Virgin Islands (U.S.)');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (241,'WF','Wallis and Futuna Islands');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (242,'EH','Western Sahara');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (243,'YE','Yemen');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (244,'ZR','Zaire');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (245,'ZM','Zambia');
INSERT INTO `country` (`id`,`code`,`name`) VALUES (246,'ZW','Zimbabwe');
